version: '3.8'

services:
  # Development environment using the actual app Dockerfile
  konditorei-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: konditorei-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - konditorei-dev-network

  # Backend API service for development
  konditorei-backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: konditorei-backend-dev
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_WIDGET_AGENT_ID=agent_6401k3d96afze6cbtcx585yqa3sa
      - REACT_APP_ENVIRONMENT=development
    networks:
      - konditorei-dev-network

  # Production build test
  konditorei-frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: konditorei-frontend-prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - konditorei-dev-network
    profiles:
      - production

  # Cleanup service to remove all containers and volumes
  cleanup:
    image: alpine:latest
    container_name: konditorei-cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        docker stop $$(docker ps -q --filter 'name=konditorei') 2>/dev/null || true &&
        docker rm $$(docker ps -aq --filter 'name=konditorei') 2>/dev/null || true &&
        docker volume rm konditorei_node_modules 2>/dev/null || true &&
        docker system prune -f
      "
    profiles:
      - cleanup

networks:
  konditorei-dev-network:
    driver: bridge
