apiVersion: v1
kind: Service
metadata:
  name: konditorei-backend-service
  namespace: chatbots
  labels:
    app: konditorei-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: konditorei-backend
