apiVersion: v1
kind: Service
metadata:
  name: konditorei-frontend-service
  namespace: ChatBots
  labels:
    app: konditorei-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: konditorei-frontend

