apiVersion: v1
kind: Secret
metadata:
  name: konditorei-github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Bionic-AI-Solutions/Konditorei.git
  username: not-used
  password: YOUR_GITHUB_TOKEN_HERE
